### ISSUE TITLE
create new login form

### ISSUE THREAD

**Issue by aliaict** [ALIAICT-TWI/Timesheet#2]
dear @mujib-rahman 
create new login web-form (sample) via visual studio

**Comment by mujib-rahman** [comment]
I created virtually

**Comment by aliaict** [comment]
ok will integrate

**Comment by aliaict** [comment]
ok thanks i reviewed 88b495aca0076861ea6e740f015f9d40482475ce it good

**Comment by aliaict** [comment]
this fix #2
